import React from 'react';

export const metadata = {
  title: 'Terms of Service | Solaris Energy Solutions',
  description: 'Terms and conditions governing the use of the Solaris Energy website, solar calculator estimates, and EPC consultation.',
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 text-slate-800 space-y-6">
      <h1 className="text-3xl font-black text-slate-900 tracking-tight">Terms of Service</h1>
      <p className="text-xs text-slate-400">Last updated: September 2026</p>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="text-lg font-bold text-slate-900">1. Nature of Solar Estimates</h2>
        <p>
          Calculations generated by the Solaris Energy Solar Calculator and proposal models are estimates based on standard global horizontal irradiation (GHI) averages and prevailing DISCOM electricity tariffs. Final generation capacity and bill offsets are finalized following an official on-site structural and shadow survey.
        </p>

        <h2 className="text-lg font-bold text-slate-900">2. Government Subsidies & Approvals</h2>
        <p>
          Subsidy disbursements under PM Surya Ghar: Muft Bijli Yojana or PM-KUSUM are governed by central and state government agencies and are subject to consumer eligibility, portal verification, and DISCOM net-meter inspection timelines.
        </p>

        <h2 className="text-lg font-bold text-slate-900">3. Intellectual Property</h2>
        <p>
          All trademarks, site designs, calculators, engineering graphics, and digital media hosted on this website are the proprietary intellectual property of Solaris Energy Solutions.
        </p>
      </section>
    </div>
  );
}
